title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  year:
    label: Year
    type:  text
    width: 1/4

  text:
    label: Text
    type:  textarea


  purl:
    label: Website
    type:  url

  thumbnail:
    label: Thumbimage
    type:  image

  imglist:
    label: Images
    type: structure
    style: table
    fields:
      title:
        label: Title
        type: text
      link:
        label: Link
        type: url        
      location:
        label: Size
        type: select
        options:
          full: Full
          half: Half
          line: Line
      image:
        label: Image
        type: image