title: Project

files:
  sortable: true

pages: false

fields:
  seo: seo
  
  title:
    label: Title
    type:  text
    width: 2/4

  year:
    label: Year
    type:  text
    width: 1/4
  
  feautured:
    label: Feautured
    type:  checkboxes
    options: 
      active: Active
    width: 1/4

  text:
    label: Text
    type:  textarea


  purl:
    label: Website
    type:  textarea

  thumbnail:
    label: Thumbimage
    type:  image

  imglist:
    label: Images
    type: structure
    style: table
    fields:
      title:
        label: Title
        type: textarea      
      location:
        label: Size
        type: select
        options:
          full: Full
          half: Half
          line: Line
          text: Text
      image:
        label: Image
        type: image
